### ISSUE TITLE
Pode ser utilizado o nestjs-cron ?

### ISSUE THREAD

**Issue by johnsontavares** [multiplierx/desafio-integracao#4]
Estava pesquisando sobre o node-cron conforme a descrição do desafio
não encontrei aplicações utilizando o node-cron com o nest.js, apenas com o node.js
É válido criar os jobs cron com o nestjs-cron para o desafio ?
att, Johnson

**Comment by Caiuriuller** [comment]
Boa noite, desculpe pela demora na resposta! Claro que sim pode utilizar o nestjs-cron.
